controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_front", "left_back"]
    right_wheel_names: ["right_front", "right_back"]
    wheels_per_side: 2
    wheel_radius: 0.13
    wheel_separation: 0.416
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    publish_rate: 50.0
    cmd_vel_timeout: 0.25
    use_stamped_vel: false
    open_loop: true
    position_feedback: false
    max_linear_velocity: 1.0
    max_angular_velocity: 1.0